labb5: fodelsedag.cpp fodelsedag.h main.cpp main.h sok.cpp sok.h tabort.cpp tabort.h Addkontakt.cpp Addkontakt.h isvalid.cpp isvalid.h visa.cpp visa.h
	g++ -o labb5 main.cpp fodelsedag.cpp tabort.cpp sok.cpp Addkontakt.cpp  isvalid.cpp visa.cpp
run: labb5
	./labb5
clean:
	rm labb5